packaging_format = 2

id = "hugo"
name = "Hugo"
description.en = "Static Site Generator"
description.fr = "Générateur de blog statique"

version = "0.150.0~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "Apache-2.0"
website = "https://gohugo.io"
admindoc = "https://gohugo.io/documentation"
code = "https://github.com/gohugoio/hugo"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/hugo"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.site_name]
    ask.en = "Choose a directory name for your site (used for `hugo new site name` command)"
    ask.fr = "Choisissez le nom de répertoire pour votre site (utilisé dans la commande `hugo new site nom`)"
    type = "string"
    default = "site"

[resources]

    [resources.sources.main]
    amd64.url = "https://github.com/gohugoio/hugo/releases/download/v0.150.0/hugo_extended_0.150.0_linux-amd64.tar.gz"
    amd64.sha256 = "d7348b78e8bbaf41a5ead308d3d4108bf18f2fb3fa203d3f0d99afa1c00bd096"
    arm64.url = "https://github.com/gohugoio/hugo/releases/download/v0.150.0/hugo_extended_0.150.0_linux-arm64.tar.gz"
    arm64.sha256 = "9416d465021a683f0365c2e7e6cc6235508fb4ae541c74bf3bd7663af62d8e15"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*amd64.tar.gz"
    autoupdate.asset.armhf = ".*arm64.tar.gz"

    [resources.system_user]
    allow_ssh = true
    allow_sftp = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "hugo"
