packaging_format = 2

id = "hugo"
name = "Hugo"
description.en = "Static Site Generator"
description.fr = "Générateur de blog statique"

version = "0.147.1~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "Apache-2.0"
website = "https://gohugo.io"
admindoc = "https://gohugo.io/documentation"
code = "https://github.com/gohugoio/hugo"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/hugo"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.site_name]
    ask.en = "Choose a directory name for your site (used for `hugo new site name` command)"
    ask.fr = "Choisissez le nom de répertoire pour votre site (utilisé dans la commande `hugo new site nom`)"
    type = "string"
    default = "site"

[resources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/gohugoio/hugo/releases/download/v0.147.1/hugo_extended_0.147.1_linux-amd64.tar.gz"
    amd64.sha256 = "7822d40360c8123a624ac8f3e4305b83908dd76cc7885ae4b00e985dac0b920f"
    arm64.url = "https://github.com/gohugoio/hugo/releases/download/v0.147.1/hugo_extended_0.147.1_linux-arm64.tar.gz"
    arm64.sha256 = "c61466b4fda9bcfaba34a7e89dca21dc5a9d8f2fcf8372d101c6ffa7d163d7a9"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*amd64.tar.gz"
    autoupdate.asset.armhf = ".*arm64.tar.gz"

    [resources.system_user]
    allow_ssh = true
    allow_sftp = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    #[resources.apt]
    #packages = "hugo"
