#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD MODIFICATIONS
#=================================================
ynh_script_progression --message="Updating system configurations related to $app..." --weight=1

ynh_change_url_nginx_config

# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app"
