#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
ynh_script_progression "Updating system configurations related to $app..."

ynh_config_change_url_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
